<?php

use Illuminate\Database\Seeder;


class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('items')->insert([
            ['name' => 'Acne Skincare', 'aisle' => 'Pharmacy'],
            ['name' => 'Air Fresheners', 'aisle' => '17'],
            ['name' => 'Ammonia', 'aisle' => '17'],
            ['name' => 'Analgesics', 'aisle' => 'Pharmacy'],
            ['name' => 'Automotive Suppliers', 'aisle' => 'Housewares'],

            ['name' => 'Baby Milk', 'aisle' => 'Infant Needs'],
            ['name' => 'Bake Ware', 'aisle' => 'Housewares'],
            ['name' => 'Baby Food', 'aisle' => 'Infant Needs'],
            ['name' => 'Baby Needs', 'aisle' => 'Infant Needs'],
            ['name' => 'Baby Wipes', 'aisle' => 'Infant Needs'],
            ['name' => 'Bagels, Bulk', 'aisle' => 'Bakery'],
            ['name' => 'Bags, Lunch', 'aisle' => '8'],
            ['name' => 'Bags, Garbage', 'aisle' => '8'],
            ['name' => 'Baking Cups', 'aisle' => '7'],
            ['name' => 'Baking Needs', 'aisle' => '7,8'],
            ['name' => 'Band Aids', 'aisle' => 'Pharmacy'],
            ['name' => 'Bar Soap', 'aisle' => 'Pharmacy'],
            ['name' => 'Bath Oil', 'aisle' => 'Cosmetics'],
            ['name' => 'Bathroom Tissue', 'aisle' => '16'],
            ['name' => 'Batteries', 'aisle' => 'Housewares'],
            ['name' => 'Beans, Baked', 'aisle' => '21'],
            ['name' => 'Beans, Dried', 'aisle' => '18'],
            ['name' => 'Beans, Canned', 'aisle' => '21'],
            ['name' => 'Beer, Non-alcoholic', 'aisle' => '2'],
            ['name' => 'Bird Seed', 'aisle' => '10'],
            ['name' => 'Biscuits', 'aisle' => '23'],
            ['name' => 'Bleach', 'aisle' => '9'],
            ['name' => 'Bread', 'aisle' => 'Bakery'],
            ['name' => 'Bread Crumbs', 'aisle' => 'Bakery'],
            ['name' => 'Briquettes', 'aisle' => 'Housewares'],
            ['name' => 'Brita Filters', 'aisle' => 'Housewares'],
            ['name' => 'Brooms', 'aisle' => '17'],
            ['name' => 'Brushes', 'aisle' => '17'],
            ['name' => 'Buns, Bulk', 'aisle' => 'Bakery'],
            ['name' => 'Butter', 'aisle' => 'Dairy'],

            ['name' => 'Cake Decorating', 'aisle' => '7'],
            ['name' => 'Cake Mixes', 'aisle' => '7'],
            ['name' => 'Cake, Frozen', 'aisle' => '14, Bakery'],
            ['name' => 'Cakes, Birthday', 'aisle' => 'Bakery'],
            ['name' => 'Calculators', 'aisle' => 'Housewares'],
            ['name' => 'Candles', 'aisle' => '7, Housewares'],
            ['name' => 'Candy', 'aisle' => '2, Bulk'],
            ['name' => 'Canning Supplies', 'aisle' => '8'],
            ['name' => 'Cards, Playing', 'aisle' => 'Housewares'],
            ['name' => 'Cat Food', 'aisle' => '10'],
            ['name' => 'Cat Litter', 'aisle' => '10'],
            ['name' => 'Cereals, Cold', 'aisle' => '6'],
            ['name' => 'Cereals, Hot', 'aisle' => '6'],
            ['name' => 'Cheese, Natural', 'aisle' => 'Deli, Diary'],
            ['name' => 'Cheese Slices', 'aisle' => 'Dairy'],
            ['name' => 'Chicken Soup Stock', 'aisle' => '3'],
            ['name' => 'Chia Seeds', 'aisle' => 'Natural Foods'],
            ['name' => 'Chips', 'aisle' => '1, 24'],
            ['name' => 'Chip Dip', 'aisle' => 'Dairy'],
            ['name' => 'Chocolates, Boxed', 'aisle' => '24'],
            ['name' => 'Chocolates, Baking', 'aisle' => '8'],
            ['name' => 'Chocolates, Chips', 'aisle' => '8'],
            ['name' => 'Cigarettes', 'aisle' => 'Gas Bar'],
            ['name' => 'Citrus Punch', 'aisle' => '3, 22'],
            ['name' => 'Cleaners', 'aisle' => '17'],
            ['name' => 'Cocktail Mixers', 'aisle' => '2'],
            ['name' => 'Cocoa', 'aisle' => '8'],
            ['name' => 'Coconut, Shredded', 'aisle' => '8'],
            ['name' => 'Coconut, Whole', 'aisle' => 'Produce'],
            ['name' => 'Coffee, Grounded', 'aisle' => '5'],
            ['name' => 'Coffee, Instant', 'aisle' => '5'],
            ['name' => 'Coffee Filters', 'aisle' => '5'],
            ['name' => 'Coffee Whitener', 'aisle' => '5'],
            ['name' => 'Coffee Makers', 'aisle' => 'Housewares'],
            ['name' => 'Coffee Mugs', 'aisle' => 'Housewares'],
            ['name' => 'Cold Cuts', 'aisle' => 'Deli, Meat'],
            ['name' => 'Computers, Tablets', 'aisle' => 'Housewares'],
            ['name' => 'Conditioner, Hair', 'aisle' => 'Cosmetics'],
            ['name' => 'Cookies', 'aisle' => '23'],
            ['name' => 'Cooking Oil', 'aisle' => '20'],
            ['name' => 'Cookware', 'aisle' => 'Housewares'],
            ['name' => 'Coolers', 'aisle' => 'Housewares'],
            ['name' => 'Corn Starch', 'aisle' => '7'],
            ['name' => 'Cottage Cheese', 'aisle' => 'Dairy'],
            ['name' => 'Cough & Cold', 'aisle' => 'Pharmacy'],
            ['name' => 'Crackers, Snack', 'aisle' => '23'],
            ['name' => 'Crackers, Soda', 'aisle' => '23'],
            ['name' => 'Cranberry Sauce', 'aisle' => '8'],
            ['name' => 'Creamers', 'aisle' => 'Dairy'],
            ['name' => 'Croutons', 'aisle' => '20'],
            ['name' => 'Crystals, Drink', 'aisle' => '22'],
            ['name' => 'Currants', 'aisle' => '8'],

            ['name' => 'Diary Products', 'aisle' => 'Dairy'],
            ['name' => 'Deli Foods', 'aisle' => 'Deli'],
            ['name' => 'Dental Floss', 'aisle' => 'Pharmacy'],
            ['name' => 'Deodorant, Personal', 'aisle' => 'Cosmetics'],
            ['name' => 'Deodorant, Carpet', 'aisle' => '17'],
            ['name' => 'Detergent, Liquid Laundry', 'aisle' => '9'],
            ['name' => 'Detergent, Powder Laundry', 'aisle' => '9'],
            ['name' => 'Diapers', 'aisle' => 'Infant Needs'],
            ['name' => 'Dinners, Frozen', 'aisle' => '12'],
            ['name' => 'Dinnerware', 'aisle' => 'Housewares'],
            ['name' => 'Dish Detergent', 'aisle' => '16'],
            ['name' => 'Distilled Water', 'aisle' => 'Pharmacy'],
            ['name' => 'Dried Beans, Peas', 'aisle' => '18'],
            ['name' => 'Dried Fruit', 'aisle' => '8'],
            ['name' => 'Donuts', 'aisle' => 'Bakery'],
            ['name' => 'Dog Food', 'aisle' => '11'],

            ['name' => 'Imported Foods', 'aisle' => '7, 18, 19'],

            ['name' => 'Eggs', 'aisle' => 'Dairy'],
            ['name' => 'Electrical', 'aisle' => '17'],
            ['name' => 'Extracts', 'aisle' => '7'],
            ['name' => 'Eye Care', 'aisle' => 'Pharmacy'],
            ['name' => 'Eye Glasses', 'aisle' => 'Optical'],

            ['name' => 'Fabric Softener', 'aisle' => '16'],
            ['name' => 'Facial Tissue', 'aisle' => '6'],
            ['name' => 'Feminine Hygiene', 'aisle' => 'Pharmacy'],
            ['name' => 'Filters (Furnace)', 'aisle' => 'Housewares'],
            ['name' => 'First Aid', 'aisle' => 'Pharmacy'],
            ['name' => 'Fish, Canned', 'aisle' => '21'],
            ['name' => 'Fish, Fresh', 'aisle' => 'Seafood'],
            ['name' => 'Fish, Frozen', 'aisle' => '14, Seafood'],
            ['name' => 'Flour', 'aisle' => '7'],
            ['name' => 'Foil Containers', 'aisle' => '7'],
            ['name' => 'Foil Wrap', 'aisle' => '8'],
            ['name' => 'Foot Care', 'aisle' => 'Pharmacy'],
            ['name' => 'Freezer Bags', 'aisle' => '8'],
            ['name' => 'French Fries, Frozen', 'aisle' => '13'],
            ['name' => 'Fruit, Frozen', 'aisle' => '12 - End'],
            ['name' => 'Fruit, Fresh', 'aisle' => 'Produce'],
            ['name' => 'Fruit Juice, Frozen', 'aisle' => '12 - End'],
            ['name' => 'Fruit Juice, Serve Ready', 'aisle' => '3, 22'],
            ['name' => 'Fruit Juice, Refrigerated', 'aisle' => 'Dairy'],

            ['name' => 'Garbage Bags', 'aisle' => '8'],
            ['name' => 'Garden Supplies', 'aisle' => 'Garden Center'],
            ['name' => 'Gift Wrap', 'aisle' => 'Housewares'],
            ['name' => 'Glue', 'aisle' => 'Houewares'],
            ['name' => 'Granola bars', 'aisle' => '4'],
            ['name' => 'Grenadine Syrup', 'aisle' => '2'],
            ['name' => 'Ground Coffee', 'aisle' => '5'],

            ['name' => 'Hair Care', 'aisle' => 'Cosmetics'],
            ['name' => 'Hand Cream, Medicated', 'aisle' => 'Pharmacy'],
            ['name' => 'Hand Cream', 'aisle' => 'Cosmetics'],
            ['name' => 'Hangers', 'aisle' => 'Housewares'],
            ['name' => 'Hardware', 'aisle' => 'Housewares'],
            ['name' => 'Honey', 'aisle' => '6'],
            ['name' => 'Hot Chocolate', 'aisle' => '5'],
            ['name' => 'Household Cleaners', 'aisle' => '17'],
            ['name' => 'Horseradish', 'aisle' => '20, Meat'],

            ['name' => 'Ice', 'aisle' => 'Front of Store Checkout #5'],
            ['name' => 'Ice Cream', 'aisle' => '12'],
            ['name' => 'Ice Cream Cones', 'aisle' => '23'],
            ['name' => 'Ice Cream Novelties', 'aisle' => '12'],
            ['name' => 'Ice Cream Topping', 'aisle' => '23'],
            ['name' => 'Ice Melt', 'aisle' => 'Houseware/ Entrance #0'],
            ['name' => 'Instant Potatoes', 'aisle' => '18'],

            ['name' => 'Jars, Canning', 'aisle' => '8'],
            ['name' => 'Jams/Jellies', 'aisle' => '6'],
            ['name' => 'Jelly Powders', 'aisle' => '8'],
            ['name' => 'Jewellery', 'aisle' => 'Cosmetics'],
            ['name' => 'Juice, Frozen', 'aisle' => '12 - End'],
            ['name' => 'Juices & Drinks', 'aisle' => '3, 22, Dairy'],

            ['name' => 'Ketchup', 'aisle' => '20'],
            ['name' => 'Kitchen bags', 'aisle' => '8'],
            ['name' => 'Kitchen Gadgets', 'aisle' => 'Housewares'],
            ['name' => 'Kool Aid', 'aisle' => '22'],
            ['name' => 'Kraft Dinner', 'aisle' => '18'],

            ['name' => 'Lard', 'aisle' => '8'],
            ['name' => 'Light Bulbs', 'aisle' => '17'],
            ['name' => 'Lunch Bags', 'aisle' => '8'],
            ['name' => 'Lunch Kits', 'aisle' => 'Housewares'],
            ['name' => 'Luncheon Meats', 'aisle' => 'Deli, Meat'],
            ['name' => 'Lysol', 'aisle' => '17'],

            ['name' => 'Macaroni & Cheese Dinners', 'aisle' => '18'],
            ['name' => 'Margarine', 'aisle' => 'Dairy'],
            ['name' => 'Marmalade', 'aisle' => '6'],
            ['name' => 'Marshmallows', 'aisle' => '8'],
            ['name' => 'Mason Jars', 'aisle' => '8'],
            ['name' => 'Mayonnaise', 'aisle' => '20'],
            ['name' => 'Meat, Canned', 'aisle' => '21'],
            ['name' => 'Meat, Fresh', 'aisle' => 'Meat, Deli'],
            ['name' => 'Meat, Frozen', 'aisle' => 'Meat'],
            ['name' => 'Meat Pies, Frozen', 'aisle' => 'Meat'],
            ['name' => 'Meat Pies, Fresh', 'aisle' => 'Deli'],
            ['name' => 'Mexican Foods', 'aisle' => '18'],
            ['name' => 'Milk, Baby', 'aisle' => 'Infant Needs'],
            ['name' => 'Milk, Canned', 'aisle' => '5'],
            ['name' => 'Milk, Fresh', 'aisle' => 'Dairy'],
            ['name' => 'Milk, Powdered', 'aisle' => '5'],
            ['name' => 'Mincemeat', 'aisle' => '8'],
            ['name' => 'Molasses', 'aisle' => '8'],
            ['name' => 'Mouthwash', 'aisle' => 'Pharmacy'],
            ['name' => 'Mustard, Dry', 'aisle' => '7'],
            ['name' => 'Mustard, Prepared', 'aisle' => '20'],

            ['name' => 'Napkins', 'aisle' => '8'],
            ['name' => 'Newspapers', 'aisle' => 'Entrance'],
            ['name' => 'Novelties, Frozen', 'aisle' => '12'],
            ['name' => 'Nuts, Salted', 'aisle' => '1, Bulk'],
            ['name' => 'Nuts, Shelled (Baking)', 'aisle' => '8, Bulk'],
            ['name' => 'Nylons', 'aisle' => 'Joe Apparel'],

            ['name' => 'Oats', 'aisle' => '6'],
            ['name' => 'Oil, Automotive', 'aisle' => 'Housewares'],
            ['name' => 'Oil, Cooking', 'aisle' => '20'],
            ['name' => 'Olive Oil', 'aisle' => '20'],
            ['name' => 'Olives', 'aisle' => '20, Deli'],
            ['name' => 'Oxo', 'aisle' => '20'],

            ['name' => 'Pablums', 'aisle' => 'Infant Needs'],
            ['name' => 'Pain Relief', 'aisle' => 'Pharmacy'],
            ['name' => 'Panko Crumbs', 'aisle' => '20'],
            ['name' => 'Pancake Flour', 'aisle' => '5'],
            ['name' => 'Pancake Mixes', 'aisle' => '5'],
            ['name' => 'Pantyhose', 'aisle' => 'Joe Apparel'],
            ['name' => 'Pasta, Fresh', 'aisle' => 'Deli'],
            ['name' => 'Pasta, Canned', 'aisle' => '21'],
            ['name' => 'Pasta, Noodles (Dry)', 'aisle' => '21'],
            ['name' => 'Pasta, Sauce', 'aisle' => '21'],
            ['name' => 'Paper Plates', 'aisle' => '8'],
            ['name' => 'Paper Goods', 'aisle' => '9, 16'],
            ['name' => 'Paper Towels', 'aisle' => '9, 16'],
            ['name' => 'Party Items', 'aisle' => 'Housewares'],
            ['name' => 'Pastries', 'aisle' => 'Bakery'],
            ['name' => 'Peanut Butter', 'aisle' => '6'],
            ['name' => 'Perogies, Frozen', 'aisle' => '14'],
            ['name' => 'Perogies, Fresh', 'aisle' => 'Deli'],
            ['name' => 'Pet Care', 'aisle' => '10'],
            ['name' => 'Pet Food', 'aisle' => '10, 11'],
            ['name' => 'Photo Developing', 'aisle' => 'Housewares'],
            ['name' => 'Photo Frames', 'aisle' => 'Housewares'],
            ['name' => 'Pie Fillings', 'aisle' => '8'],
            ['name' => 'Pie, Frozen', 'aisle' => '14'],
            ['name' => 'Pillows', 'aisle' => 'Housewares'],
            ['name' => 'Pickles', 'aisle' => '20'],
            ['name' => 'Pizza, Fresh', 'aisle' => 'Deli'],
            ['name' => 'Pizza, Frozen', 'aisle' => '15'],
            ['name' => 'Pizza, Mixes', 'aisle' => '21'],
            ['name' => 'Plant Pots', 'aisle' => 'Garden Centre'],
            ['name' => 'Plants Floral', 'aisle' => 'Produce, Garden Centre'],
            ['name' => 'Pop', 'aisle' => '3, 22'],
            ['name' => 'Pop Tarts', 'aisle' => '4'],
            ['name' => 'Popping Corn', 'aisle' => '2'],
            ['name' => 'Pork & Beans', 'aisle' => '21'],
            ['name' => 'Potato Chips', 'aisle' => '1, 24'],
            ['name' => 'Potatoes, Instant', 'aisle' => '18'],
            ['name' => 'Potting Soil', 'aisle' => 'Garden Centre'],
            ['name' => 'Powdered Cleansers', 'aisle' => '17'],
            ['name' => 'Prunes', 'aisle' => '8, Bulk'],
            ['name' => 'Puddings, Powder', 'aisle' => '8'],
            ['name' => 'Puddings, Ready', 'aisle' => '4'],


        ]);

    }
}
