<?php

use Illuminate\Database\Seeder;


class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('items')->insert([
            ['name' => 'Acne Skincare', 'aisle' => 'Pharmacy'],
            ['name' => 'Air Fresheners', 'aisle' => '17'],
            ['name' => 'Ammonia', 'aisle' => '17'],
            ['name' => 'Analgesics', 'aisle' => 'Pharmacy'],
            ['name' => 'Automotive Suppliers', 'aisle' => 'Housewares'],
            ['name' => 'Baby Milk', 'aisle' => 'Infant Needs'],
            ['name' => 'Bake Ware', 'aisle' => 'Housewares'],
            ['name' => 'Baby Food', 'aisle' => 'Infant Needs'],
            ['name' => 'Baby Needs', 'aisle' => 'Infant Needs'],
            ['name' => 'Baby Wipes', 'aisle' => 'Infant Needs'],
            ['name' => 'Bagels, Bulk', 'aisle' => 'Bakery'],
            ['name' => 'Bags, Lunch', 'aisle' => '8'],
            ['name' => 'Bags, Garbage', 'aisle' => '8'],
            ['name' => 'Baking Cups', 'aisle' => '7'],
            ['name' => 'Baking Needs', 'aisle' => '7,8'],
            ['name' => 'Band Aids', 'aisle' => 'Pharmacy'],
            ['name' => 'Bar Soap', 'aisle' => 'Pharmacy'],
            ['name' => 'Bath Oil', 'aisle' => 'Cosmetics'],
            ['name' => 'Bathroom Tissue', 'aisle' => '16'],
            ['name' => 'Batteries', 'aisle' => 'Housewares'],
            ['name' => 'Beans, Baked', 'aisle' => '21'],
            ['name' => 'Beans, Dried', 'aisle' => '18'],
            ['name' => 'Beans, Canned', 'aisle' => '21'],
            ['name' => 'Beer, Non-alcoholic', 'aisle' => '2'],
            ['name' => 'Bird Seed', 'aisle' => '10'],
            ['name' => 'Biscuits', 'aisle' => '23'],
            ['name' => 'Bleach', 'aisle' => '9'],
            ['name' => 'Bread', 'aisle' => 'Bakery'],
            ['name' => 'Bread Crumbs', 'aisle' => 'Bakery'],
            ['name' => 'Briquettes', 'aisle' => 'Housewares'],
            ['name' => 'Brita Filters', 'aisle' => 'Housewares'],
            ['name' => 'Brooms', 'aisle' => '17'],
            ['name' => 'Brushes', 'aisle' => '17'],
            ['name' => 'Buns, Bulk', 'aisle' => 'Bakery'],
            ['name' => 'Butter', 'aisle' => 'Dairy'],
            ['name' => 'Cake Decorating', 'aisle' => '7'],
            ['name' => 'Cake Mixes', 'aisle' => '7'],
            ['name' => 'Cake, Frozen', 'aisle' => '14, Bakery'],
            ['name' => 'Cakes, Birthday', 'aisle' => 'Bakery'],
            ['name' => 'Calculators', 'aisle' => 'Housewares'],
            ['name' => 'Candles', 'aisle' => '7, Housewares'],
            ['name' => 'Candy', 'aisle' => '2, Bulk'],
            ['name' => 'Canning Supplies', 'aisle' => '8'],
            ['name' => 'Cards, Playing', 'aisle' => 'Housewares'],
            ['name' => 'Cat Food', 'aisle' => '10'],
            ['name' => 'Cat Litter', 'aisle' => '10'],
            ['name' => 'Cereals, Cold', 'aisle' => '6'],
            ['name' => 'Cereals, Hot', 'aisle' => '6'],
            ['name' => 'Cheese, Natural', 'aisle' => 'Deli, Diary'],
            ['name' => 'Cheese Slices', 'aisle' => 'Dairy'],
            ['name' => 'Chicken Soup Stock', 'aisle' => '3'],
            ['name' => 'Chia Seeds', 'aisle' => 'Natural Foods'],
            ['name' => 'Chips', 'aisle' => '1, 24'],
            ['name' => 'Chip Dip', 'aisle' => 'Dairy'],
            ['name' => 'Chocolates, Boxed', 'aisle' => '24'],
            ['name' => 'Chocolates, Baking', 'aisle' => '8'],
            ['name' => 'Chocolates, Chips', 'aisle' => '8'],
            ['name' => 'Cigarettes', 'aisle' => 'Gas Bar'],
            ['name' => 'Citrus Punch', 'aisle' => '3, 22'],
            ['name' => 'Cleaners', 'aisle' => '17'],
            ['name' => 'Cocktail Mixers', 'aisle' => '2'],
            ['name' => 'Cocoa', 'aisle' => '8'],
            ['name' => 'Coconut, Shredded', 'aisle' => '8'],
            ['name' => 'Coconut, Whole', 'aisle' => 'Produce'],
            ['name' => 'Coffee, Grounded', 'aisle' => '5'],
            ['name' => 'Coffee, Instant', 'aisle' => '5'],
            ['name' => 'Coffee Filters', 'aisle' => '5'],
            ['name' => 'Coffee Whitener', 'aisle' => '5'],
            ['name' => 'Coffee Makers', 'aisle' => 'Housewares'],
            ['name' => 'Coffee Mugs', 'aisle' => 'Housewares'],
            ['name' => 'Cold Cuts', 'aisle' => 'Deli, Meat'],
            ['name' => 'Computers, Tablets', 'aisle' => 'Housewares'],
            ['name' => 'Conditioner, Hair', 'aisle' => 'Cosmetics'],
            ['name' => 'Cookies', 'aisle' => '23'],
            ['name' => 'Cooking Oil', 'aisle' => '20'],
            ['name' => 'Cookware', 'aisle' => 'Housewares'],
            ['name' => 'Coolers', 'aisle' => 'Housewares'],
            ['name' => 'Corn Starch', 'aisle' => '7'],
            ['name' => 'Cottage Cheese', 'aisle' => 'Dairy'],
            ['name' => 'Cough & Cold', 'aisle' => 'Pharmacy'],
            ['name' => 'Crackers, Snack', 'aisle' => '23'],
            ['name' => 'Crackers, Soda', 'aisle' => '23'],
            ['name' => 'Cranberry Sauce', 'aisle' => '8'],
            ['name' => 'Creamers', 'aisle' => 'Dairy'],
            ['name' => 'Croutons', 'aisle' => '20'],
            ['name' => 'Crystals, Drink', 'aisle' => '22'],
            ['name' => 'Currants', 'aisle' => '8'],
        ]);

    }
}
